### ISSUE TITLE
ALL FILES 

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.fr-fr#1]
All files in image folder are untranslated yet

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Set the Art locfile in Prehandoff status, waiting for check In locrepo.

**Comment by stonezy123** [comment]
Now, all the image was translated.
https://github.com/MicrosoftLearning/AI-102-AIEngineer.fr-fr/tree/OLPRODLOC/Instructions/images
